eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka,http://localhost:8761/eureka
#  instance:
#    virtual-host-name: microservice-provider
# virtual-host-name默认跟spring.application.name一致
server:
  port:
    9998
spring:
  application:
    name: microservice-provider