eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka,http://localhost:8761/eureka
server:
  port: 7766
spring:
  application:
    name: feign-client
feign:
  client:
    config:
      microservice-provider:
        loggerLevel: full
  hystrix:
    enabled: true
  ribbon:
      ReadTimeout: 0
      ConnectTimeout: 0
      MaxAutoRetries: 0
      MaxAutoRetriesNextServer: 0
      OkToRetryOnAllOperations: false
      eureka:
        enabled: false
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000
logging:
  level:
    com.silence.spring.cloud.feign.service.FeignInterface: DEBUG