spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://source.enncloud.cn/dev.laikang.com/diviner-config-server.git
          username:
#          searchPaths: config-file
    label: master
server:
  port: 7788
